INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 586, in _request
    await resp.start(conn)
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 905, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chort\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram:Bot: RiasBet \U0001f48b [@RiasBetBot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
